# Optimizaciones para GALY XNOVATEC
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true

# Desactivamos flags de 16KB para usar el modo de extracción compatible (Legacy)
android.bundle.enable16kAlignment=false
android.enable16kAlignment=false
android.useUncompressedNativeLibs=false

# Parallel sync
org.gradle.tooling.parallel=true
